
package at.ac.tuwien.dsg.sybl.controlService.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import at.ac.tuwien.dsg.sybl.localService.utils.Configuration;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ControlService", targetNamespace = "http://main.controlService.sybl.dsg.tuwien.ac.at/", wsdlLocation = "http://localhost:8080/ControlService-0.0.1-SNAPSHOT/ControlService?wsdl")
public class ControlService
    extends Service
{

    private final static URL CONTROLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(at.ac.tuwien.dsg.sybl.controlService.service.ControlService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = at.ac.tuwien.dsg.sybl.controlService.service.ControlService.class.getResource(".");
            url = new URL(baseUrl, Configuration.getCloudServiceURL());
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: "+ Configuration.getCloudServiceURL()+", retrying as a local file");
            logger.warning(e.getMessage());
        }
        CONTROLSERVICE_WSDL_LOCATION = url;
    }

    public ControlService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControlService() {
        super(CONTROLSERVICE_WSDL_LOCATION, new QName("http://main.controlService.sybl.dsg.tuwien.ac.at/", "ControlService"));
    }

    /**
     * 
     * @return
     *     returns SyblControlWebService
     */
    @WebEndpoint(name = "SyblControlWebServicePort")
    public SyblControlWebService getSyblControlWebServicePort() {
        return super.getPort(new QName("http://main.controlService.sybl.dsg.tuwien.ac.at/", "SyblControlWebServicePort"), SyblControlWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SyblControlWebService
     */
    @WebEndpoint(name = "SyblControlWebServicePort")
    public SyblControlWebService getSyblControlWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://main.controlService.sybl.dsg.tuwien.ac.at/", "SyblControlWebServicePort"), SyblControlWebService.class, features);
    }

}
