
package at.ac.tuwien.dsg.sybl.controlService.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SyblControlWebService", targetNamespace = "http://main.controlService.sybl.dsg.tuwien.ac.at/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SyblControlWebService {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    public void processAnnotation(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        SyblAnnotation arg1);

}
